### ISSUE TITLE
关于接口时效性的疑问

### ISSUE THREAD

**Issue by Matt-wzy** [imhansai/weifangbus#1]
作者您好，请问您是怎样拿到接口的呢？我这边在使用代码调用16路（顺/逆行）公交车实时信息的时候遇上了问题，通过对比发现在编译出来的程序中也会报错Bad state: No element，仔细观察以及抓包对比发现目前版本的潍坊掌上公交使用的接口有所更换，例如，其app在开屏获取全部路线信息时发送的指令为
`http://122.4.254.30:7501/BusService/Query_AllSubRouteData/?timeStamp=20231010205835&Random=974&SignKey=b81e35944ff4b2ec1e0e99492b0379df21f7162a3ebe0d449ba4aa0e041e21d7&PackageName=com.hisense.wfbus2`
其中有关16路返回值为`,{"RouteID":1601,"RouteName":"16路顺行","IsHaveSubRouteCombine":"0","Sortinfo":0,"RouteNameExt":null}，`
以及获取公交车实时信息的接口地址也有所变动（这个不确定是不是入口的问题），
`http://122.4.254.30:7501/BusService/Query_ByStationIDReturnAll/?RouteID=%40E%3F%40&StationID=DD%40F%3FAA%3F%40D%3FFA%3FH%3F%3F%3F%3F%3F&IsmainsubCombine=%3F&timeStamp=20231010210322&Random=873&SignKey=f414a10c1e1123128646aa1de6e4df1efd743ac61aa5bdfbbaefdbf14144f720&PackageName=com.hisense.wfbus2`
请问作者有兴致更新一下相关的代码么？

**Comment by imhansai** [comment]
我是利用技术手段砸壳后直接看源代码。代码有段时间没有更新了，可能官方的接口改变了，明天我看一下:)
想不到这还有人折腾呢，哈哈哈

**Comment by Matt-wzy** [comment]
> 我是利用技术手段砸壳后直接看源代码。代码有段时间没有更新了，可能官方的接口改变了，明天我看一下:) 想不到这还有人折腾呢，哈哈哈

啊-哈，竟然秒回了，感谢回复
以及稍微提醒一下，可能需要拿到最新的app再敲壳，我手机上这个版本号是1.9.3，应该是潍坊掌上公交这个app的最新版了（我在应用宝下的），我看应用宝上的更新记录这个版本应该是今年三月份的，比上次commit的时间要早一些/////
折腾只是为了每天抓固定线路然后数据多了就有把握哪班车会不会迟到之类的（阿哲）（这算不算某种意义上的“大数据”呢）
题外话说多了，经过观察以及测试发现参数基本上就是换了接口没换算法（我用chatgpt把[encryptedString](https://github.com/imhansai/weifangbus/blob/81fb9b2cf724fa9c80413d2be56b5610b17ede53/lib/util/request_params_util.dart#L45) 这个函数转换到了python之后发现python的weekday是从0开始的，但测试之后发现应该是从1开始，我对flutter了解不多不清楚会怎样），经典的换汤不换药了。
（写到这里边写边查发现老接口好像也能用？把自己都给绕晕了，不过目前本仓库的代码查询16路这种是提示网络错误，总之就是感谢作者回复啦~）

**Comment by imhansai** [comment]
今天测试了 Query_AllSubRouteData 和 Query_ByStationIDReturnAll 接口，可以获取到数据。如果你使用python的话，需要检查一下python实现的签名部分是否OK:)

有时间打算也改为类似官方时间线的UI,更符合现在的接口返回的数据结构

![image](https://github.com/imhansai/weifangbus/assets/17228526/95546aae-41c2-422d-90f6-4d116fd87aca)

**Comment by Matt-wzy** [comment]
> 打算也改为类似官方时间线的UI,更符合现在的接口返回的数据结

加油！听上去就是超大的工作量呢~

顺顺便八卦一下，作者既然不是潍坊人主要也不在潍坊活动的话为什么会做潍坊的这个公交车的工具呢((((((

**Comment by imhansai** [comment]
因为我毕业第一份工作就在潍坊，工作了三年，虽然后面离开了，哈哈

**Comment by Matt-wzy** [comment]
> 因为我毕业第一份工作就在潍坊，工作了三年，虽然后面离开了，哈哈

希望潍坊这个地方没有让你失望透顶吧(((((

说起来潍坊哪片有计算机或者互联网有关的企业啊？在这生活了这么久了竟然不知道

（不过潍坊那个应届生人才补贴当时领了么）

**Comment by imhansai** [comment]
没有啊，潍坊挺好的，遇到了人生中重要的人，挺好的。潍坊歌尔不错，当时挺多同事都去了那里。看样子你是刚毕业，加油吧:)
祝你早日完成数据分析，永不迟到，哈哈，这个issue就先关闭了，可以邮件、微信联系:)
